
[[main]]
  name = "Docs"
  url = "/docs/start-here/golang/"
# url = "/docs/1.0/start-here/getting-started/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 30


# [[main]]
#   name = "Other docs"
#   url = "https://github.com/thuliteio/doks/discussions"
#   weight = 50
#   identifier = "other-docs"
#
# [[main]]
#   name = "Thulite"
#   weight = 51
#   url = "https://docs.thulite.io/"
#   parent = "other-docs"
#
# [[main]]
#   name = "Images"
#   weight = 52
#   url = "https://images.thulite.io/"
#   parent = "other-docs"

# [[main]]
#   name = "Inline SVG"
#   weight = 53
#   url = "https://svg.thulite.io/"
#   parent = "other-docs"
#
# [[main]]
#   name = "SEO"
#   weight = 54
#   url = "https://seo.thulite.io/"
#   parent = "other-docs"

[[social]]
  name = "GitHub"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-github" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path></svg>'
  url = "https://github.com/KhanbalaRashidov"
  post = "v1.3.0"
  weight = 10

[[social]]
  name = "Instagram"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M7.75,2A5.75,5.75,0,0,0,2,7.75v8.5A5.75,5.75,0,0,0,7.75,22h8.5A5.75,5.75,0,0,0,22,16.25v-8.5A5.75,5.75,0,0,0,16.25,2Zm0,2h8.5A3.75,3.75,0,0,1,20,7.75v8.5A3.75,3.75,0,0,1,16.25,20h-8.5A3.75,3.75,0,0,1,4,16.25v-8.5A3.75,3.75,0,0,1,7.75,4ZM18,7.5a.75.75,0,1,0,.75.75A.75.75,0,0,0,18,7.5ZM12,7.25a4.75,4.75,0,1,0,4.75,4.75A4.75,4.75,0,0,0,12,7.25Zm0,2a2.75,2.75,0,1,1-2.75,2.75A2.75,2.75,0,0,1,12,9.25Z"/></svg>'
  url = "https://www.instagram.com/rashidov.khanbala"
  weight = 20

[[social]]
  name = "LinkedIn"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M21,21H17V14.25C17,13.19 15.81,12.31 14.75,12.31C13.69,12.31 13,13.19 13,14.25V21H9V9H13V11C13.66,9.93 15.36,9.24 16.5,9.24C19,9.24 21,11.28 21,13.75V21M7,21H3V9H7V21M5,3A2,2 0 0,1 7,5A2,2 0 0,1 5,7A2,2 0 0,1 3,5A2,2 0 0,1 5,3Z"/></svg>'
  url = "https://www.linkedin.com/in/rashidov-khanbala-b67453182/"
  weight = 30



[[sidebar_upgrade-guides]]
  name = "Upgrade to v1"
  pageRef = "/upgrade-guides/upgrade-to-v1/"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  url = "https://thulite.io/privacy/"
  weight = 10

[[footer]]
  name = "Terms of Service"
  url = "https://thulite.io/terms/"
  weight = 20
